version: '3'

networks:
  xarxa_projecte02:
    driver: bridge

services:
  projecte02:
    image: gp1f5a1:3.0
    volumes:
      - ./app:/var/www/html
    expose:
      - "80"
    networks:
      - xarxa_projecte02

  lb:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - projecte02
    ports:
      - "8080:8000"
    networks:
      - xarxa_projecte02
